flashcard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('', include('flashcards.urls')), 
]

flashcards/urls.py
from django.urls import path

from . import views

app_name = 'flashcards'

urlpatterns = [
    path('', views.index, name='index'),
    path('edit/<int:level_id>/', views.edit, name='edit'),
    path('delete/<int:level_id>/', views.delete, name='delete'),
    path('quiz/<int:level_id>/', views.quiz, name='quiz'),
    path('practice', views.practice, name='practice'),
    path('select_level', views.select_level, name='select_level'),
    path('about', views.about, name='about'),
]

users/urls.py
"""Define URLs for users"""

from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from . import views

app_name = 'users'

urlpatterns = [
    #login page
    path('login/', LoginView.as_view(template_name='users/login.html'), 
        name='login'),
    #logout page
    path('logout/', views.logout_view, name='logout'),
    #Registration page
    path('register/', views.register, name='register'),
]

flashcards/models.py
import datetime

from django.contrib.auth.models import User
from django.db import models

class Level(models.Model):
    """ A level is a set of questions (+answers) """
    name = models.CharField(max_length=200)

    def __str__(self):
        representation = self.name
        return representation

class QuestionAnswer(models.Model):
    """This will be the cue shown to the user"""
    question = models.CharField(max_length=200)
    answer = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    level = models.ForeignKey(Level, on_delete=models.CASCADE)

    def __str__(self):
        representation = str(self.question) + ": " + self.answer
        return representation

class LevelUser(models.Model):
    level = models.ForeignKey(Level, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    topscore = models.PositiveSmallIntegerField()
    topscore_perc_m = models.FloatField(blank=True,
                                        null=True,
                                        default=0)
    
    def award(self):
        potential_score = QuestionAnswer.objects.filter(level=self.level).count()
        if self.topscore == potential_score:
            return "🥇"
        elif self.topscore/potential_score >= .8:
            return "🥈"
        elif self.topscore/potential_score >= .5:
            return "🥉"
        else:
            return ""
    
    def __str__(self):
        return str(self.user) + "'s top score on " + str(self.level) + " is " + str(self.topscore)

flashcards/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.db.models.functions import Lower
from django.http import HttpResponseBadRequest, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, reverse

from .helper import new_question_list
from .models import QuestionAnswer, Level, LevelUser

def index(request):
    context = {}
    context["show_practice"] = False

    if request.user.is_authenticated:
        levels_with_topscore = LevelUser.objects.filter(
            user=request.user,topscore_perc_m=1)

        if len(levels_with_topscore) > 0:
            context["show_practice"] = True

    return render(request, 'flashcards/index.html', context)

def about(request):
    return render(request, 'flashcards/about.html')

def select_level(request):
    # if next_page is not given, default to quiz
    if request.method == 'POST':
        next_page = request.POST.get("next_page")
    else:
        next_page = "quiz"

    levels = Level.objects.order_by(Lower('name'))

    awards = {}

    if request.user.is_authenticated:
        for level in LevelUser.objects.filter(user=request.user):
            awards[level.level.id] = level.award()

    if "question_list" in request.session:
        del request.session["question_list"]
    if "score" in request.session:
        del request.session["score"]
        
    context = {'levels': levels,
               'awards': awards,
               'next_page': next_page,
               }

    return render(request, 'flashcards/select_level.html', context)

def quiz(request, level_id):
    level = get_object_or_404(Level,id=level_id)

    # if there's an answer in the request, we check if it's correct, add 1 to
    # the score and give back the question and the answer.

    prev_question = {}
    if "answer" in request.POST:
        question = QuestionAnswer.objects.get(id=request.POST.get("question_id"))

        if(str.lower(request.POST.get("answer")) == question.answer):
            prev_question["correct"] = True
            request.session["score"] += 1
        else:
            prev_question["correct"] = False
        
        prev_question["question"] = question

    # we make a shuffled question_id list if there is none. If there is, we 
    # check if the list is empty because if so the quiz is done end we show
    # the end view and update the top score.

    if "question_list" not in request.session:
        # new quiz: fill question_list
        request.session["score"] = 0
        question_list = new_question_list(level)
    else:
        question_list = request.session["question_list"]

        if question_list == []: # quiz is done
            score = request.session["score"]
            potential_score = QuestionAnswer.objects.filter(
                level=level).count()
            context = {'score': score,
                       'level': level,
                       'potential_score': potential_score,
                       'prev_question': prev_question,
                       'award': "",}
            if request.user.is_authenticated:
                try:
                    topscore = LevelUser.objects.get(
                        level_id=level_id,user=request.user).topscore
                except LevelUser.DoesNotExist:
                    topscore = 0

                if score >= topscore:
                    LevelUser.objects.filter(level_id=level_id, 
                                             user=request.user).delete()
                    new_leveluser = LevelUser()
                    new_leveluser.level = Level.objects.get(pk=level_id)
                    new_leveluser.user = request.user
                    new_leveluser.topscore = score
                    new_leveluser.topscore_perc_m = score/potential_score
                    new_leveluser.save()
                    context["award"] = new_leveluser.award()

            del request.session["question_list"]
            del request.session["score"]
            return render(request, 'flashcards/end.html', context)


    current_question = QuestionAnswer.objects.get(pk=question_list.pop())

    if current_question.level != level:
        print("Yeah this is not the correct level.")
        request.session["score"] = 0
        question_list = new_question_list(level)

    request.session["question_list"] = question_list
    
    context = {'current_question': current_question,
               'prev_question': prev_question,
               'score': request.session["score"],
               'level_id': level_id,
               }
    return render(request, 'flashcards/quiz.html', context)

def practice(request):
    # if there's an answer in the request, we check if it's correct, add 1 to
    # the score and give back the question and the answer.

    prev_question = {}
    if "answer" in request.POST:
        question = QuestionAnswer.objects.get(id=request.POST.get("question_id"))

        if(str.lower(request.POST.get("answer")) == question.answer):
            prev_question["correct"] = True
            if(request.session["nr_tries"] < settings.LENGTH_PRACTICE):
                request.session["score"] += 1
        else:
            prev_question["correct"] = False
        
        request.session["nr_tries"] += 1
        prev_question["question"] = question

    # if there is no question list in the session, we take ten random questions
    if "question_list" not in request.session:
        if request.user.is_authenticated:
           question_list = list(
                QuestionAnswer.objects.filter(
                    level__leveluser__user=request.user).filter(
                    level__leveluser__topscore_perc_m=1).order_by('?').values_list('id',
                    flat = True)[:settings.LENGTH_PRACTICE]
                )
        else:
            return HttpResponseBadRequest()

        if question_list == []:
            return HttpResponseBadRequest()

        request.session["score"] = 0
        request.session["nr_tries"] = 0
    # if there is a question_list we are midpractice so we get the list
    else:
        question_list = request.session["question_list"]

    #if the previous question was wrong we put it back into the question list
    if prev_question.get("correct") == False:
        question_list.insert(0,request.POST.get("question_id"))

    # if the list is there and it is empty, the practice is done
    if question_list == []:
        award = ""
        if request.session["score"] == settings.LENGTH_PRACTICE:
            award = "🥇"

        context = {'score': request.session["score"],
                   'potential_score': settings.LENGTH_PRACTICE,
                   'prev_question': prev_question,
                   'award': award,}

        del request.session["question_list"]
        del request.session["score"]

        return render(request, 'flashcards/end.html', context)

    # the current question we get from the question_id list
    current_question = QuestionAnswer.objects.get(pk=question_list.pop())

    request.session["question_list"] = question_list
    

    context = {'current_question': current_question,
               'prev_question': prev_question,
               'score': request.session["score"],
               'question_list': question_list}

    return render(request, 'flashcards/practice.html', context)




@login_required
def edit(request,level_id):
    if level_id != 0:
        level = get_object_or_404(Level,id=level_id)
    else:
        level = Level()
        level.save()

    if request.method != 'POST':
        text_rep = ""
        for question_answer in(QuestionAnswer.objects.filter(level_id=level_id).order_by('id')):
            text_rep += question_answer.question + ","
            text_rep += question_answer.answer + "\r\n"

        context = {'text_rep': text_rep,
                   'level': level,
                  }
        return render(request, 'flashcards/edit.html', context)
    else:
        # We will update the name of the level and the related questions.
        try:
            name = request.POST.get("name")
        except ValueError:
            return HttpResponseBadRequest()
        level.name = name
        level.save()

        QuestionAnswer.objects.filter(level_id=level_id).delete()
        try:
            text_rep = request.POST.get("text_rep").split("\r\n")
        except ValueError:
            return HttpResponseBadRequest()

        for line in text_rep:
            question_answer = line.split(",")
            if len(question_answer) == 2:
                new_questionanswer = QuestionAnswer()
                new_questionanswer.question = question_answer[0]
                new_questionanswer.answer = question_answer[1]
                new_questionanswer.level = level
                new_questionanswer.save()
            else:
                next

        return HttpResponseRedirect(reverse('flashcards:index'))

@login_required
def delete(request,level_id):
    level = get_object_or_404(Level,id=level_id)
    level.delete()
    
    return HttpResponseRedirect(reverse('flashcards:index'))

flashcards/templates/flashcards/about.html
{% extends "flashcards/base.html" %}
{% load bootstrap4 %}

{% block content %}
  <div class="jumbotron">
    <div>
      <h4>About this webpage</h4>
      This page is originally written for fun and educational purpose, aimed to 
      help myself getting started on recognizing characters in Asian 
      (specifically Buddhist) calligrapy.
      When I showed it to people around me I received enthusiastic reactions so
      I decided to improve usability and keep it online. <br /><br />
      The inspiration for making this page came entirely from reading 
      <a href="https://www.amazon.com/Heart-Brush-Splendor-Asian-Calligraphy/dp/1611801346">
      Heart of the Brush: The Splendor of East Asian Calligraphy</a> by Kaz 
      Tanahashi.
      The book displays wonderful calligraphy based on 150 characters, which 
      formed the curriculum for this page. <br />
      <br />
      This page is written and maintained by 
      <a href="https://www.linkedin.com/in/maartenfugers/">Maarten Fugers</a>.
      If you have questions or comments, please send me a message on LinkedIn!
    </div>
    <br />
    <a class="btn btn-secondary btn-block" href="{% url 'flashcards:index' %}" role="button">
      Back
    </a>
  </div>
{% endblock content %}

flashcards/templates/flashcards/base.html
{% load bootstrap4 %}
{% load static %}

<!DOCTYPE html>
<html lang='en'>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Learning Chinese characters</title>
    
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'flashcards/favicon/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'flashcards/favicon/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'flashcards/favicon/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'flashcards/favicon/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'flashcards/favicon/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'flashcards/favicon/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'flashcards/favicon/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'flashcards/favicon/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'flashcards/favicon/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'flashcards/favicon/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'flashcards/favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'flashcards/favicon/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'flashcards/favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'flashcards/favicon/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'flashcards/favicon/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">

    {% bootstrap_css %}
    <script
      src="https://code.jquery.com/jquery-3.3.1.min.js"
      integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
      crossorigin="anonymous"></script>
    {% bootstrap_javascript %}

    <style>
      .chinese_font{
        font-family: "KaiTi", "楷体", STKaiti, "华文楷体", serif;
        font-size: 64px;
      }
      .container{
        width:360px;
      }
    </style>
      
  </head>

  <body>
    <nav class="navbar navbar-light bg-light mb-3">
      <a class="navbar-brand" href="{% url 'flashcards:index' %}">
        <img src="{% static 'flashcards/favicon/favicon-32x32.png' %}" />
        Learning Chinese characters
      </a>
    </nav>

    <div class="container">
      {% block content %}{% endblock content %}
    </div>
  </body>
</html>

flashcards/templates/flashcards/edit.html
{% extends "flashcards/base.html" %}
{% load bootstrap4%}

{% block content %}

  <script type="text/javascript">
    window.onload = function() {
      document.getElementById("id_del_button").disabled = true;
      document.getElementById("id_checkbox").checked = false;
    };

    function allowDeleteOrNot() {
      var del_button = document.getElementById("id_del_button");
      
      if(document.getElementById("id_checkbox").checked == true){
        del_button.disabled = false;
      } else {
        del_button.disabled = true;
      }
    }
  </script>

  <div class="formgroup">
    <form action="{% url 'flashcards:edit' level.id %}" method = 'post'>
      {% csrf_token %}

      <input type="text" name="name" maxlength="200" value="{{ level.name }}" 
      class="form-control" />

      <textarea name="text_rep" rows="10" maxlength="2000" 
      class="form-control">{{ text_rep }}</textarea>
      
      <button name="submit" class="form-control btn-primary btn-block mt-3 mb-3">
        Submit
      </button>
    </form>

    <form action="{% url 'flashcards:delete' level.id %}" method = 'post'>
      {% csrf_token %}
      <div class="btn-group-toggle" data-toggle="buttons">
        <label class="btn btn-secondary btn-block active" aria-pressed="false" autocomplete="off"
        onmouseup="allowDeleteOrNot()">
          <input type="checkbox" id = "id_checkbox"/> 
          I want to delete this level
        </label>
      </div>
      <button name="submit" class="form-control btn-danger btn-block mt-3 mb-3"
      id = "id_del_button">
        Delete this level
      </button>
    </form>
  </div>

{% endblock content %}

flashcards/templates/flashcards/end.html
{% extends "flashcards/base.html" %}
{% load bootstrap4 %}

{% block content %}
  {% if prev_question %}
    {% if prev_question.correct == True %}
      ✅
    {% else %}
      ❌
    {% endif %}
    {{ prev_question.question.question }} = {{ prev_question.question.answer }}
  {% else %}
    <br />
  {% endif %}
  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      {% if level %}
        <h4>You have finished: {{ level.name }}</h4>
      {% else %}
        <h4>You have finished random practice!</h4>
      {% endif %}
      
      <h1>Score: {{ score }}/{{ potential_score }}</h1>
      <h1>{{ award }}</h1>
      <a class="btn btn-primary" href="{% url 'flashcards:index' %}" role="button">
        Back
      </a>
    </div>
  </div>
{% endblock content %}

flashcards/templates/flashcards/index.html
{% extends "flashcards/base.html" %}
{% load bootstrap4 %}
{% load static %}

{% block content %}
<div class="card borders-0 rounded-0 card-top-image">
  <img class="card-img img-fluid" src="{% static 'flashcards/freeimage-13680082-web.jpg' %}" 
  alt="background image">
  <div class="card-img-overlay">
    <br /><br /><br /><br /><br /><br /><br /><br />
    <a class="btn btn-primary btn-block" href="{% url 'flashcards:select_level' %}" 
    role="button">
        Start quiz
    </a>
    {% if show_practice %}
    <a class="btn btn-primary btn-block" href="{% url 'flashcards:practice' %}" 
      role="button">
      Practice your finished levels
    </a>
    {% endif %}
    {% if user.is_authenticated %}
      <a class="btn btn-secondary btn-block" href="{% url 'users:logout' %}" 
      role="button">
        Log out {{ user.username }}
      </a>
    {% else %}
      <a class="btn btn-secondary btn-block" href="{% url 'users:register' %}" 
      role="button">
        Register
      </a>
      <a class="btn btn-secondary btn-block" href="{% url 'users:login' %}" role="button">
        Log in
      </a>
    {% endif %}
    <a class="btn btn-secondary btn-block" href="{% url 'flashcards:about' %}" 
      role="button">
      About
    </a>
    {% if user.is_staff %}
      <form action="{% url 'flashcards:select_level' %}" method = 'post'>
      {% csrf_token %}
      <div class="formgroup">
        <input type="hidden" name="next_page" value = "edit">
        <button name="submit" class="btn btn-dark btn-block mt-2 mb-2">
          Edit
        </button>
      </div>
    {% endif %}
  </div>
</div> 
{% endblock content %}

flashcards/templates/flashcards/practice.html
{% extends "flashcards/base.html" %}
{% load bootstrap4 %}

{% block content %}

    {% if prev_question %}
      {% if prev_question.correct == True %}
        🟢
      {% else %}
        🔴
      {% endif %}
      {{ prev_question.question.question }} = {{ prev_question.question.answer }}
    {% else %}
      <br />
    {% endif %}
  <div class = "chinese_font">{{ current_question.question }}</div><br />
  <form action="{% url 'flashcards:practice' %}" method = 'post'>
    {% csrf_token %}
    <div class="formgroup">
      <input type="text" name="answer" maxlength="200" id="id_answer" autofocus 
      placeholder="answer..." class="form-control" />
      <input type="hidden" name="question_id" value = "{{ current_question.id }}">
      <button name="submit" class="btn btn-primary btn-block mt-3 mb-3">
        Submit
      </button>
    </div>

  </form>
{% endblock content %}

flashcards/templates/flashcards/quiz.html
{% extends "flashcards/base.html" %}
{% load bootstrap4 %}

{% block content %}
  <p>
    Score: {{ score }}
  </p>
    {% if prev_question %}
      {% if prev_question.correct == True %}
        ✅
      {% else %}
        ❌
      {% endif %}
      {{ prev_question.question.question }} = {{ prev_question.question.answer }}
    {% else %}
      <br />
    {% endif %}
  <div class = "chinese_font">{{ current_question.question }}</div><br />
  <form action="{% url 'flashcards:quiz' level_id %}" method = 'post'>
    {% csrf_token %}
    <div class="formgroup">
      <input type="text" name="answer" maxlength="200" id="id_answer" autofocus 
      placeholder="answer..." class="form-control" />
      <input type="hidden" name="question_id" value = "{{ current_question.id }}">
      <button name="submit" class="btn btn-primary btn-block mt-3 mb-3">
        Submit
      </button>
    </div>

  </form>
  
{% endblock content %}

flashcards/templates/flashcards/select_level.html
{% extends "flashcards/base.html" %}
{% load bootstrap4 %}
{% load static %}

{% block content %}
<div class="card borders-0 rounded-0 card-top-image">
  <img class="card-img img-fluid" src="{% static 'flashcards/freeimage-13680082-web.jpg' %}" 
  alt="background image">
  <div class="card-img-overlay">
    <br /><br /><br /><br /><br /><br /><br /><br />
    {% for level in levels %}
      <a class="btn btn-primary btn-block" role="button" href=
      {% if next_page == "edit" %}
        "{% url 'flashcards:edit' level.id %}" 
      {% else %}
        "{% url 'flashcards:quiz' level.id %}"
      {% endif %}
    >
      {{ level.name }}
      {% for level_id, award in awards.items %}
        {% if level_id == level.id %}
        {{ award }}
        {% endif %}
      {% endfor %}
    </a>
    {% endfor %}
    {% if next_page == "edit" %}
      <a class="btn btn-dark btn-block" href="{% url 'flashcards:edit' 0 %}" role="button">
        Add level
      </a>
    {% endif %}
    <a class="btn btn-secondary btn-block" href="{% url 'flashcards:index' %}" role="button">
      Back
    </a>
  </div>
</div> 
{% endblock content %}